name = "Mono_dance_4k"
notes = "created via web dashboard"

[source]
path = "../../sources/Mono_dance_4k.mp4"
sha256 = "5f35eb54aaa6baf5e80c00b78369ae0791ae0113def90834d1781ea158c8f247"

[erp]
width = 8000
height = 4000
fps = 60.000

[frames]
start = 0
end = 589

[viewport]
yaw_deg = -41.1
pitch_deg = 24.2
fov_h_deg = 59.0
width = 1920
height = 1080

[inner]
x = 194
y = 140
width = 1690
height = 903

[ai_clip]
path = 'E:\360AIGC\vrpatch\cases\Mono_dance_4k\AIGC_60fps.mp4'
