"""Sidecar metadata schema and JSON I/O.

A sidecar describes, per time segment, a *fixed* rectilinear viewport and the
inner rect (the person region to be regenerated by the external AI tool). The
outer ring of the viewport (everything outside `inner`) is the "margin" that
stays fixed on paste-back to anchor the seam.
"""

import json
from dataclasses import dataclass, field, asdict


@dataclass
class Viewport:
    yaw_deg: float
    pitch_deg: float
    fov_h_deg: float
    width: int
    height: int


@dataclass
class InnerRect:
    x: int
    y: int
    width: int
    height: int


@dataclass
class Segment:
    id: str
    frame_start: int
    frame_end: int  # inclusive
    viewport: Viewport
    inner: InnerRect


@dataclass
class Sidecar:
    erp_width: int
    erp_height: int
    fps: float
    segments: list = field(default_factory=list)
    version: int = 1


def sidecar_to_dict(s: Sidecar) -> dict:
    return asdict(s)


def sidecar_from_dict(d: dict) -> Sidecar:
    segs = []
    for sd in d["segments"]:
        segs.append(
            Segment(
                id=sd["id"],
                frame_start=sd["frame_start"],
                frame_end=sd["frame_end"],
                viewport=Viewport(**sd["viewport"]),
                inner=InnerRect(**sd["inner"]),
            )
        )
    return Sidecar(
        erp_width=d["erp_width"],
        erp_height=d["erp_height"],
        fps=d["fps"],
        segments=segs,
        version=d.get("version", 1),
    )


def save_sidecar(s: Sidecar, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(sidecar_to_dict(s), f, indent=2, ensure_ascii=False)


def load_sidecar(path) -> Sidecar:
    with open(path, "r", encoding="utf-8") as f:
        return sidecar_from_dict(json.load(f))
